# This workflow will run unit tests

name: Run Unit Tests
on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-timeout pytest-cov

      - name: Test Skill Patcher
        run: |
          pytest tests/skill_patch_tests.py --doctest-modules --junitxml=tests/skill-patch-test-results.xml
      - name: Upload skill patch test results
        uses: actions/upload-artifact@v2
        with:
          name: skill-patch-test-results
          path: tests/skill-patch-test-results.xml

      - name: Test Parse Utils
        run: |
          pytest tests/parse_util_tests.py --doctest-modules --junitxml=tests/parse-util-test-results.xml
      - name: Upload parse utils test results
        uses: actions/upload-artifact@v2
        with:
          name: parse-util-test-results
          path: tests/parse-util-test-results.xml

      - name: Test Transcript Utils
        run: |
          pytest tests/transcript_util_tests.py --doctest-modules --junitxml=tests/transcript-util-test-results.xml
      - name: Upload transcript util test results
        uses: actions/upload-artifact@v2
        with:
          name: transcript-util-test-results
          path: tests/transcript-util-test-results.xml

      - name: Test Web Utils
        run: |
          pytest tests/web_util_tests.py --doctest-modules --junitxml=tests/web-util-test-results.xml
      - name: Upload web utils test results
        uses: actions/upload-artifact@v2
        with:
          name: web-util-test-results
          path: tests/web-util-test-results.xml

      - name: Test Net Utils
        run: |
          pytest tests/net_util_tests.py --doctest-modules --junitxml=tests/net-util-test-results.xml
      - name: Upload net utils test results
        uses: actions/upload-artifact@v2
        with:
          name: net-util-test-results
          path: tests/net-util-test-results.xml